/**
 * Vector Document Model
 * Represents a document stored in vector database
 */

export interface VectorDocument {
  /** Unique document ID */
  id: string;

  /** Document content/text */
  content: string;

  /** Document metadata */
  metadata: VectorDocumentMetadata;

  /** Embedding vector (optional - generated by vector store) */
  embedding?: number[];

  /** Similarity score (populated during search) */
  score?: number;
}

export interface VectorDocumentMetadata {
  /** Source type (confluence, jira, etc.) */
  source: string;

  /** Source ID (page ID, ticket ID, etc.) */
  sourceId: string;

  /** Document title */
  title: string;

  /** Space key (for Confluence) */
  spaceKey?: string;

  /** Project key (for JIRA) */
  projectKey?: string;

  /** Page type */
  type?: string;

  /** Creation timestamp */
  createdAt?: string;

  /** Last modified timestamp */
  modifiedAt?: string;

  /** Additional custom metadata */
  [key: string]: any;
}
